name: Main Checks

on: [push]

jobs:
  test-node:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        node-version: [6.x, 8.x, 10.x, 12.x, 14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Configure npm registry time machine
      run: |
        npm config set registry https://time-machines-npm.sealsecurity.io/
        npm config set //time-machines-npm.sealsecurity.io/:_authToken=2022-03-30T00:12:21.829000Z
    - run: npm install
    - name: Run test with Node.js ${{ matrix.node-version }}
      run: npm run test-node
  test-karma:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        node-version: [14.x]
        bundler: [webpack, browserify]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Configure npm registry time machine
      run: |
        npm config set registry https://time-machines-npm.sealsecurity.io/
        npm config set //time-machines-npm.sealsecurity.io/:_authToken=2022-03-30T00:12:21.829000Z
    - run: npm install
    - name: Run karma tests
      run: npm run test-karma
      env:
        BUNDLER: ${{ matrix.bundler }}
  pack:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.x
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - name: Configure npm registry time machine
      run: |
        npm config set registry https://time-machines-npm.sealsecurity.io/
        npm config set //time-machines-npm.sealsecurity.io/:_authToken=2022-03-30T00:12:21.829000Z
    - run: npm install
    - name: Build dist bundles
      run: npm run build
    - name: Pack npm tarball
      run: npm pack
    - name: Upload npm tarball
      uses: actions/upload-artifact@v4
      with:
        name: npm-tarball
        path: node-forge-1.3.1.tgz
        if-no-files-found: error
#  lint:
#    runs-on: ubuntu-latest
#    timeout-minutes: 10
#    strategy:
#      matrix:
#        node-version: [14.x]
#    steps:
#    - uses: actions/checkout@v2
#    - name: Use Node.js ${{ matrix.node-version }}
#      uses: actions/setup-node@v1
#      with:
#        node-version: ${{ matrix.node-version }}
#    - run: npm install
#    - name: Run eslint
#      run: npm run lint
